### PR TITLE
arbitrary array added

### PR DESCRIPTION
**Pull request by rpietruc**
is there any better method to generate an arbitrary array of given length?

### CODE REVIEW

**Comment by philipp-classen** [comment]
Hi Rafał

with this change, I added support for std::array with this patch:
https://github.com/grogers0/CppQuickCheck/pull/6

It is similar to your patch, but handles shrinking a bit different and does not use the std::vector implementation internally.

Please take a look if the solution works for your use case, too. If it does, I will merge it.

**Comment by rpietruc** [comment]
Hi Philipp,
Thank you for adding array support, that works for me of course.
However, could you add 'example/TestReverseArray.cpp' file to project to make it compile?

**Comment by philipp-classen** [comment]
Good point. I added the missing file.

**Comment by philipp-classen** [comment]
Closed, as the feature has been merged with #6.

**Pull request closed without merging**
